---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
namespace: default
metadata:
  name: test
spec:
  clusterNetwork:
    pods:
      cidrBlocks: ["192.168.0.0/16"]
    services:
      cidrBlocks: ["10.96.0.0/12"]
